home_redirect:
    path:     /
    defaults:  
        _controller: FrameworkBundle:Redirect:redirect
        route: votop_core_home
        permanent: true

votop_core:
    resource: "@VotopCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale} 
    requirements: 
            _locale: en|fr|de
            
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale} 
    requirements: 
            _locale: en|fr|de
            
votop_user:
    resource: "@VotopUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale} 
    requirements: 
            _locale: en|fr|de
            
votop_admin:
    resource: "@VotopAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    requirements: 
            _locale: en|fr|de
            
votop_virtual_visit:
    resource: "@VotopVirtualVisitBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/visit
    requirements: 
            _locale: en|fr|de