votop_user:
    resource: "@VotopUserBundle/Resources/config/routing.yml"
    prefix:   /

votop_admin:
    resource: "@VotopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
votop_virtual_visit:
    resource: "@VotopVirtualVisitBundle/Resources/config/routing.yml"
    prefix:   /
 
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"