votop_admin:
    resource: "@VotopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

votop_platform:
    resource: "@VotopPlatformBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"