votop_core:
    resource: "@VotopCoreBundle/Resources/config/routing.yml"
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
votop_user:
    resource: "@VotopUserBundle/Resources/config/routing.yml"

votop_admin:
    resource: "@VotopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
votop_virtual_visit:
    resource: "@VotopVirtualVisitBundle/Resources/config/routing.yml"
    prefix:   /visit