votop_admin_redirect:
    path:     /
    defaults:  
        _controller: FrameworkBundle:Redirect:redirect
        route: votop_admin_dashboard
        permanent: true
        
votop_admin_dashboard:
    path:     /dashboard
    defaults: { _controller: VotopAdminBundle:Admin:dashboard }