votop_admin_dashboard:
    path:     /dashboard
    defaults: { _controller: VotopAdminBundle:Admin:dashboard }
    
votop_admin_redirect:
    path:     /
    defaults: { _controller: VotopAdminBundle:Admin:dashboard }
