homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: Default/homepage.html.twig
        _locale: '%locale%'
        
list_ordered:
    path:     /sortby/{column}
    controller: App\Controller\User\UserController::listOrderedBy